export const LOAD_ALL_PRODUCT_SUCCESS = 'LOAD_ALL_PRODUCT_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const TABLE_ROW_EXPAND = 'TABLE_ROW_EXPAND';
