export const ON_SELECT_PRODUCT_TO_CHECK = 'ON_SELECT_PRODUCT_TO_CHECK';
export const ON_CHECK_PRODUCT_QUANTITY_CHANGE = 'ON_CHECK_PRODUCT_QUANTITY_CHANGE';
export const ON_REMOVE_CHECK_ITEM_FROM_LIST = 'ON_REMOVE_CHECK_ITEM_FROM_LIST';
export const ON_INVENT_NOTE_INPUT_CHANGE = 'ON_INVENT_NOTE_INPUT_CHANGE';
export const ON_CREATE_TEMP_INVENT_CHECK_SUCCESS = 'ON_CREATE_TEMP_INVENT_CHECK_SUCCESS';
export const ON_CREATE_INVENT_CHECK_SUCCESS = 'ON_CREATE_INVENT_CHECK_SUCCESS';
