export const LOAD_ALL_CUSTOMER_SUCCESS = 'LOAD_ALL_CUSTOMER_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const TABLE_ROW_EXPAND = 'TABLE_ROW_EXPAND';
