export const LOAD_ALL_RECEIPTS_SUCCESS = 'LOAD_ALL_RECEIPTS_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const RECEIPT_TABLE_ROW_EXPAND = 'RECEIPT_TABLE_ROW_EXPAND';
export const HANDLE_RECEIPT_SEARCH = 'HANDLE_RECEIPT_SEARCH';
