export const LOAD_ALL_INVENT_NOTES_SUCCESS = 'LOAD_ALL_INVENT_NOTES_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const INVENT_TABLE_ROW_EXPAND = 'INVENT_TABLE_ROW_EXPAND';
export const HANDLE_INVENT_NOTE_SEARCH = 'HANDLE_INVENT_NOTE_SEARCH';
