export const LOAD_ALL_PROVIDER_SUCCESS = 'LOAD_ALL_PROVIDER_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const UPDATE_PROVIDER_SUCCESS = 'UPDATE_PROVIDER_SUCCESS';
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS';
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS';
export const TABLE_ROW_EXPAND = 'TABLE_ROW_EXPAND';
